-
  id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://test-kratos-public:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://ory.test.info/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

-
  id: "ory:kratos:admin"
  upstream:
    preserve_host: true
    url: "http://test-kratos-admin:4434"
    strip_path: /.ory/kratos/private
  match:
    url: "http://ory.test.info/.ory/kratos/private/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: remote_json
    config:
      remote: http://keto-api:4456/check
      payload: |
        {
          "namespace": "access",
          "object": "administration",
          "relation": "access",
          "subject": "{{print .Extra.identity.traits.role }}"
        }
  mutators:
    - handler: id_token

-
  id: "ory:kratos-admin-ui-node:protected"
  upstream:
    preserve_host: true
    url: "http://admin-ui:3000"
    strip_path: /admin
  match:
    url: "http://ory.test.info/admin/<**>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: remote_json
    config:
      remote: http://keto-api:4456/check
      payload: |
        {
          "namespace": "access",
          "object": "administration",
          "relation": "access",
          "subject": "{{print .Extra.identity.traits.role }}"
        }
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://ory.test.info/panel/auth/login

-
  id: "ory:kratos-selfservice-ui-node:anonymous"
  upstream:
    preserve_host: true
    url: "http://selfservice:4455"
    strip_path: /panel
  match:
    url: "http://ory.test.info/panel/<{error,recovery,verify,auth/*,**.css,**.js}{/,}>"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

-
  id: "ory:kratos-selfservice-ui-node:protected"
  upstream:
    preserve_host: true
    url: "http://selfservice:4455"
    strip_path: /panel
  match:
    url: "http://ory.test.info/panel/<{,debug,dashboard,settings}>"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: remote_json
    config:
      remote: http://keto-api:4456/check
      payload: |
        {
          "namespace": "access",
          "object": "application",
          "relation": "access",
          "subject": "{{print .Extra.identity.traits.role }}"
        }
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://ory.test.info/panel/auth/login